# Generated by Django 4.2 on 2023-09-11 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(verbose_name='이름')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='은행')),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='은행')),
                ('balance', models.IntegerField(default=0, verbose_name='잔액')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.money')),
            ],
        ),
    ]
