# Generated by Django 4.2.2 on 2023-09-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_alter_bank_bank_name_alter_money_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='bank_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='money.bank', verbose_name='은행'),
        ),
    ]
