# Generated by Django 4.2.2 on 2023-09-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_alter_money_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(choices=[('bank1', '국민은행'), ('bank2', '농협은행'), ('bank3', '신한은행')], default='bank1', max_length=20, verbose_name='은행'),
        ),
    ]
