# Generated by Django 4.2 on 2023-09-13 08:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_alter_money_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no_to', models.CharField(max_length=20, verbose_name='받는 계좌번호')),
                ('account_no_from', models.CharField(max_length=20, verbose_name='주는 계좌번호')),
                ('account_bank_to', models.CharField(choices=[('국민', '국민은행'), ('신한', '신한은행'), ('우리', '우리은행'), ('하나', '하나은행'), ('농협', '농협은행'), ('기업', '기업은행'), ('토스', '토스뱅크'), ('카카오', '카카오뱅크')], max_length=10, verbose_name='받는 은행')),
                ('account_bank_from', models.CharField(choices=[('국민', '국민은행'), ('신한', '신한은행'), ('우리', '우리은행'), ('하나', '하나은행'), ('농협', '농협은행'), ('기업', '기업은행'), ('토스', '토스뱅크'), ('카카오', '카카오뱅크')], max_length=10, verbose_name='주는 은행')),
                ('user_to', models.CharField(max_length=20, verbose_name='받는 사람')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10'))], verbose_name='금액')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.money')),
            ],
        ),
    ]
