# Generated by Django 4.2 on 2023-09-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='account_bank_from',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='account_no_from',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='timestamp',
        ),
    ]
