# Generated by Django 4.2 on 2023-09-18 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0005_remove_transfer_account_bank_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='받는 사람'),
        ),
    ]
