# Generated by Django 4.2 on 2023-09-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_alter_transfer_user_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='money',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_as_money', to='money.money'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_as_user_to', to='money.money', verbose_name='받는 사람'),
        ),
    ]
