# Generated by Django 4.2 on 2023-09-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_alter_bank_bank_name'),
        ('money', '0007_alter_transfer_money_alter_transfer_user_to'),
    ]

    operations = [
    ]
