# Generated by Django 4.2 on 2023-09-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_merge_20230919_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='은행'),
        ),
    ]
