# Generated by Django 4.2.2 on 2023-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='default_value_here', max_length=20, null=True, unique=True, verbose_name='이름'),
        ),
    ]
